### ISSUE TITLE
Dataset Image Preview exit on click outside of image

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/hub-temp#1]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Allow user to exit an image preview by clicking anywhere outside an image:

<img width="1143" alt="Screenshot 2021-11-15 at 23 26 35" src="https://user-images.githubusercontent.com/26833433/141866067-75f04b7b-2677-4c63-9ffa-6009ef6443b4.png">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by kalenmike** [comment]
This has been added to the current development build and will be deployed with the next release.

**Comment by stefani-kovachevska** [comment]
Escape key is quite useful too.
