### ISSUE TITLE
'Create Model' Requires Refresh to Appear in Project

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/hub-temp#10]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models, Projects

### Bug

I use the 'Create Mode' popup to create a model, but once the popup disappears the Project page is empty, my model does not appear:
<img width="1321" alt="Screenshot 2021-11-20 at 12 55 16" src="https://user-images.githubusercontent.com/26833433/142725429-710e1620-5d25-41e0-a2c4-a7fc8f14f152.png">

If I refresh the page the model now appears:
<img width="1321" alt="Screenshot 2021-11-20 at 12 55 24" src="https://user-images.githubusercontent.com/26833433/142725422-2d65c0b9-9fc9-48df-9318-224d7e4dfe41.png">

### Environment

MacOS
Chrome

**Comment by kalenmike** [comment]
This appears to be resolved now.
