### ISSUE TITLE
'Enter' key to save changes in Models/Projects/Datasets/Model pages.

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/hub-temp#11]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Hitting 'Enter' key to save changes in Models/Projects/Datasets/Model pages is probably a good idea. I tried to do this by instinct a few times and found it not enabled.

The four areas I tried to do this were Models/Projects/Datasets/Model, but maybe this should be default behavior for any editable text box in the HUB?

### Additional

This would add to https://github.com/ultralytics/hub-temp/issues/9, which saves changes on clicking outside the boxes, and works well.

**Comment by kalenmike** [comment]
This has been implemented.

**Comment by glenn-jocher** [comment]
Awesome! I think will really speed up workflows.
