### ISSUE TITLE
Unlimited Project title input breaks screen

### ISSUE THREAD

**Issue by stefani-kovachevska** [ultralytics/hub-temp#12]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Projects

### Bug

<img width="1440" alt="testing" src="https://user-images.githubusercontent.com/89992912/143366721-a3b09d91-996f-4d60-81bd-2b734736beb4.png">

I've entered too long of a project title and it's all over my screen. 👀  

### Environment

- Computer: MacBook Air M1
- OS: macOS Monterey 12.0.1
- Browser: Brave 1.32.106 and Chrome 96.0.4664.55

### Minimal Reproducible Example

1. Log into HUB
2. Projects list -> Create a project with a long title 
3. Navigate to the newly created Project -> Model list
4. Voila!

**Comment by kalenmike** [comment]
Capped the length of the title and description in projects for the next release.
