### ISSUE TITLE
Deleting a project name does not reset to default

### ISSUE THREAD

**Issue by stefani-kovachevska** [ultralytics/hub-temp#13]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Projects

### Bug

I've deleted all chars from the Project's name input and updated the Project item. 

- Expected output: Project name reset to default (Untitled Project)
- Actual output: see screenshots attached:

The project's name in the Project list is empty. 
<img width="1440" alt="Screenshot 2021-11-25 at 03 33 59" src="https://user-images.githubusercontent.com/89992912/143368194-e9aaa16c-9928-4475-9bca-1ae48e8db0d0.png">

The breadcrumb inside the project (Project -> Model list) returns null
<img width="1440" alt="Screenshot 2021-11-25 at 03 34 04" src="https://user-images.githubusercontent.com/89992912/143368140-ac8754dc-dda4-48ee-9cde-2c4b392025f8.png">

### Environment

- Computer: MacBook Air M1
- OS: macOS Monterey 12.0.1
- Browser: Brave 1.32.106 and Chrome 96.0.4664.55

### Minimal Reproducible Example

1. Log into HUB
2. Create a project 
3. Edit its name: delete all chars
4. Navigate inside the updated project (Project -> Model list)

**Comment by kalenmike** [comment]
Updated to be deployed on next release.
