### ISSUE TITLE
Onboarding information visible on all HUB screens

### ISSUE THREAD

**Issue by stefani-kovachevska** [ultralytics/hub-temp#14]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

There is a label and a button on the top left on each screen as I navigate through HUB. 
- Label: Onboarding 
- Button: Change step

<img width="1438" alt="Pasted Graphic 3" src="https://user-images.githubusercontent.com/89992912/143370771-bb72b2bf-d117-488c-8c47-7795462ac168.png">

### Environment

- HUB version: v0.1.0-beta - 18:46 22.11.2021 +01:00
- Computer: MacBook Air M1
- OS: macOS Monterey 12.0.1
- Browser: Brave 1.32.106 and Chrome 96.0.4664.55

### Additional

Not sure if this is a bug or an in-development feature, but it should be removed from production env until ready.

**Comment by kalenmike** [comment]
This was a setting for your user that has been changed. The onboard is still in progress and will not show for new users at the moment.
