### ISSUE TITLE
Add confirmation on delete item actions

### ISSUE THREAD

**Issue by stefani-kovachevska** [ultralytics/hub-temp#15]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Adding a confirmation modal to item lists could prevent users from accidentally deleting their projects.   
i.e. "Are you sure you want to do this?" 

### Use case

Perhaps something similar:
https://dribbble.com/shots/14590249-Delete-Dialog

It's a standard to avoid user frustration, especially in cases when the user's work would significantly be impacted since some of our activities in the user flow take hours/days to complete:
- the model is training
- the dataset is uploading
- the project contains model(s)

**Comment by glenn-jocher** [comment]
@stefani-kovachevska @kalenmike I think a gmail approach is probably best, so the delete action is single-click, but then the little notice at the bottom lingers for maybe 5 seconds with an 'Undo' button.

**Comment by stefani-kovachevska** [comment]
The Gmail toast message with undo action is suitable for non-critical actions such as email deletion, whereas we have actions that could revoke hours/days of work. Also, in Gmail's example, there's a Trash list feature from where you can find accidentally deleted emails.

The toast message used disappears in seconds, and if the action was clicked by accident, the user might not see it or react fast enough. :D

UX article on both features @glenn-jocher 
https://uxplanet.org/toast-notification-or-dialog-box-ae32ad53106d

**Comment by kalenmike** [comment]
@glenn-jocher @stefani-kovachevska I already started work on the quick undo 'Gmail approach'. What you are asking for Stef is pretty much already implemented so I can easily add it. I just need confirmation on which route we are going.

**Comment by glenn-jocher** [comment]
@stefani-kovachevska yes good points. The 'full gmail' system (toast, trash can, single-click actions, multi-item selection, sorting, searching) would be the awesome to have eventually, they clearly know a thing or two over there.

I'd like to avoid multi-click actions because these are pain points of mine in W&B. To delete a model I have to click 3 times: actions > delete > confirm. This becomes tedious if I want to delete multiple models from a project at the same time.

@kalenmike is there any easy way to implement a gmail-style trash can system that users can clean up or restore items from?

**Comment by kalenmike** [comment]
@glenn-jocher We can implement a trash can. It's not a quick job but also not something that would take too long. Unlike Gmail we have several different types of data (projects, models, datasets VS emails). So we would probably want to copy GDrive. This feature one way or the other is a priority.

In order of development speed:
1 - Confirmation modal. (As implemented when clicking 'Delete Account' on hub.ultralytics.com/settings/profile) est. 10 minutes
2 - Toast Undo Option. (As partly implemented when deleting a project on /projects) est. 2 hours
3 - Trash can, requires toast (#2) est. 3 days

Let me know which one you want for this current release.

**Comment by glenn-jocher** [comment]
@kalenmike got it! Let's do both 1 and 2 for MVP. 3 we'll leave for the longer roadmap.
