### ISSUE TITLE
Account Settings -> Breadcrumb remembers last visited menu item

### ISSUE THREAD

**Issue by stefani-kovachevska** [ultralytics/hub-temp#16]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Settings

### Bug

The breadcrumb listed a few different menu items when in Account Settings:

<img width="1440" alt="Account Settings" src="https://user-images.githubusercontent.com/89992912/143372415-fc26e427-8de0-4e3c-9381-a4f94a08f506.png">

<img width="1440" alt="Screenshot 2021-11-25 at 04 01 15" src="https://user-images.githubusercontent.com/89992912/143372445-f9507ec0-0084-4e3c-8ad2-6bb98eccad61.png">

### Environment

HUB version: v0.1.0-beta - 18:46 22.11.2021 +01:00
Computer: MacBook Air M1
OS: macOS Monterey 12.0.1
Browser: Brave 1.32.106 and Chrome 96.0.4664.55

### Minimal Reproducible Example

1. Log into HUB
2. Navigate to Settings
3. Navigate to Datasets
4. Navigate to Settings again

### Additional

@kalenmike it seems that you've added a task in the _Know issues_ that's marked check, not sure if it's complete:
- Breadcrumbs do not follow the user's navigation

**Comment by kalenmike** [comment]
This has been fixed for the next deployement.
