### ISSUE TITLE
Improve UX on list item action buttons

### ISSUE THREAD

**Issue by stefani-kovachevska** [ultralytics/hub-temp#17]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

As a user, I want to effortlessly select the action I intend to take (editing or deleting a list item) instead of going back-and-forth through the screens because I have accidentally missed the button for a few mm. 😂 
- Project list
- Model list
- Dataset list

### Use case

Currently, the pointing cursor (indicating a link 👆) is visible on the full list item surface because it's a clickable UI element we use for navigation. 

The action button icons' highlight on hover is barely noticeable and the user has to try hard to actually hit the proper button (edit/delete), otherwise, their whole view will change and they will have to go back to the previous screen.

https://user-images.githubusercontent.com/89992912/143375562-72cd0a21-f9fb-452c-b77c-97e631334f69.mp4

### Additional

A way we can improve this is if we can apply a Google Mail similar style so that the quick action icons have a bit of padding and colored background. @AlanDimmer shoot if you have a better idea.

![image](https://user-images.githubusercontent.com/89992912/143376552-c59326e3-f587-4216-ae9a-1a6c1339df41.png)

**Comment by kalenmike** [comment]
The icon container is now clickable and a circle is visible on hover. To be deployed on next release.
