### ISSUE TITLE
Login issue, Google Chrome, my chrome is outdated though fyi.

### ISSUE THREAD

**Issue by johnk2hawaii** [ultralytics/hub-temp#18]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

![Screenshot from 2021-11-24 22-01-46](https://user-images.githubusercontent.com/64561921/143403136-dcbdce9c-a5cf-4a99-8209-71893f660855.png)
Working on a dusty ubuntu 18.04 computer. Will try after an update

### Environment

Dell xps 1360

**Comment by kalenmike** [comment]
This has been fixed and your login will be working now.
