### ISSUE TITLE
Recover Password: Create a confirmation page

### ISSUE THREAD

**Issue by AlanDimmer** [ultralytics/hub-temp#19]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

When I press the button to reset my password, in the page nothing happen.

### Use case

When I press the button to reset my password the system sends an email to my Gmail but I don't have any confirmation. 
The button remains in the same state and it looks like you should press it again. For the user it may seem like a bug, but we need a confirmation that the email was sent.

**Comment by kalenmike** [comment]
For the moment the button text changes, there is a confirmation page in the pipeline.
