### ISSUE TITLE
Display per-class dataset statistics

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/hub-temp#2]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Display number of labels per class.

<img width="1265" alt="Screenshot 2021-11-15 at 23 33 03" src="https://user-images.githubusercontent.com/26833433/141863494-7ecff688-e603-4cf2-bd6e-d9717dfdc2b0.png">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by kalenmike** [comment]
This has been added to the current development build and will be deployed with the next release.
