### ISSUE TITLE
Agent disconnected -> Model status not updated

### ISSUE THREAD

**Issue by stefani-kovachevska** [ultralytics/hub-temp#20]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models

### Bug

1. I have started training a model that got stuck on 97%. 

![image](https://user-images.githubusercontent.com/89992912/143423911-739be741-5c5c-4f69-9249-2e8652cef35f.png)

2. I came back several hours later, realized it was disconnected and had to reconnect it in Colab.

<img width="1440" alt="Screenshot 2021-11-25 at 11 18 43" src="https://user-images.githubusercontent.com/89992912/143423998-898410ed-0a77-42d8-b9af-b045501c138a.png">

3. I tried reconnecting and it resulted in "ModuleNotFoundError" error messages. 

![Collab-capture](https://user-images.githubusercontent.com/89992912/143424966-d3a1973b-474d-4868-9ccf-9073479c99dc.png)

Expected result: Model status updated to 'Failed - Connection Lost' as per scope agreement. The exception should ideally be caught instead of showing a console error message.

### Environment

- HUB version: v0.1.0-beta - 18:46 22.11.2021 +01:00
- Computer: MacBook Air M1
- OS: macOS Monterey 12.0.1
- Browser: Brave 1.32.106 and Chrome 96.0.4664.55

### Minimal Reproducible Example

1. Login to HUB
2. Create a project
3. Create a model
4. Start training 
5. Disconnect agent due to inactivity 
6. Come back to/refresh agent
7. Reconnect agent
8. Refresh model

### Additional

Assuming this is a bug according to the status feature included in the MVP scope. An additional enhancement will go in hand with the 'Resume training' feature that is not yet developed.

**Comment by kalenmike** [comment]
Training cannot currently be resumed, I raised this with @glenn-jocher recently.

**Comment by kalenmike** [comment]
Timeout is now shown if last response was greater than one hour.
