### ISSUE TITLE
https://hub.ultralytics.com/settings/api-keys does not go to API key page

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/hub-temp#23]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

When a user clicks the API key page link https://hub.ultralytics.com/settings/api-keys from the [Colab notebook](https://colab.research.google.com/github/ultralytics/hub/blob/master/hub.ipynb) they will end up at the home screen.

### Environment

- MacOS
- Chrome
- Safari also happens

### Minimal Reproducible Example

1. Go to https://hub.ultralytics.com/settings/api-keys/
2. Land on home page instead of API keys page

### Additional

Let's shorten the URL to just /keys (like https://github.com/settings/keys) and then also create an easier to remember redirect we can use for our notebook etc., https://ultralytics.com/keys

**Comment by kalenmike** [comment]
@glenn-jocher Thanks for pointing this out. There was a recent change to the routing behaviour that caused this issue. It has been fixed for the next deployment.
