### ISSUE TITLE
Double checkpoint upload

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/hub-temp#24]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

A second model training will upload the current training and the previous training checkpoint.

<img width="1630" alt="Screenshot 2021-11-29 at 13 26 43" src="https://user-images.githubusercontent.com/26833433/143868354-d1cf13e5-b83e-4269-a5dc-3d81be24fd6c.png">

### Environment

- MacOS
- Chrome
- Colab Notebook

### Minimal Reproducible Example

Login to HUB and notebook and then:

1. Create Model A in HUB
2. Train Model A in Notebook (wait until finished)
3. Create model B in HUB
4. Train Model B in Notebook (observe double checkpoint upload)

**Comment by kalenmike** [comment]
@glenn-jocher To confirm this is happening with the same colab notebook open?

**Comment by glenn-jocher** [comment]
> @glenn-jocher To confirm this is happening with the same colab notebook open?

Yes.

**Comment by glenn-jocher** [comment]
@kalenmike double checkpointing is fixed in `ultralytics>=0.0.48`

IMPORTANT: Fix requires up-to-date master yolov5/yolov5-pro, both up to date now
