### ISSUE TITLE
Invalid URLs allowed in HUB:  https://hub.ultralytics.com/work

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/hub-temp#27]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

I accidentally typed in https://hub.ultralytics.com/work (meant to go to https://ultralytics.com/work to see open positions, and page was allowed (auto-signin happened) with no 404 message. 

![Uploading Screen Shot 2021-12-10 at 1.13.42 PM.png…]()

### Environment

- MacOS
- Chrome 96

### Minimal Reproducible Example

Go to https://hub.ultralytics.com/work

### Additional

We probably want to redirect these to the 404 announcement and skip signing for invalid URLs. Maybe Alan should make a new HUB 404.

**Comment by kalenmike** [comment]
Added 404 page to v0.1.7-beta
