### ISSUE TITLE
Slim Rectangle Image Previews Off-Screen

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/hub-temp#29]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

<img width="1607" alt="Screen Shot 2021-12-23 at 1 20 25 PM" src="https://user-images.githubusercontent.com/26833433/147239894-00031e83-be48-44b9-97b2-b337750df4ea.png">

<img width="1381" alt="Screen Shot 2021-12-23 at 1 21 43 PM" src="https://user-images.githubusercontent.com/26833433/147239979-d2042b12-05c9-453d-b35b-d567ebab0b5b.png">

### Environment

- MacOS
- Chrome

### Minimal Reproducible Example

1. Go to VOC Dataset
2. Select Airplane class
3. Scroll down a few screens and click image above

**Comment by kalenmike** [comment]
Fixed for release v0.1.10-beta

**Comment by glenn-jocher** [comment]
@kalenmike awesome!!!
