### ISSUE TITLE
Train/Val/Test statistics are not updating correctly

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/hub-temp#3]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

Dataset statistics shown apply only for Train set. When a user clicks on Validate tab, statistics should update to Val set statistics, and same applies for Test set. Note that Test set will usually not contain any labels, so statistics will mostly be zeros (this is ok).

All statistics should update, i.e. Total image, unlabelled images, etc. 

<img width="1265" alt="Screenshot 2021-11-15 at 23 33 03 2" src="https://user-images.githubusercontent.com/26833433/141863687-d9e9ac5e-2d64-4983-8393-8901bfe4b754.png">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by kalenmike** [comment]
Changes added to the current development build and will be deployed with the next release.
