### ISSUE TITLE
Datasets tab not showing Classes, Images, Unlabelled

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/hub-temp#4]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

Datasets tab has 3 dots in place of statistics. User should see statistics here for entire dataset (train + val + test).

<img width="1282" alt="Screenshot 2021-11-15 at 23 39 24" src="https://user-images.githubusercontent.com/26833433/141864024-ff2a1c85-b808-4d87-8872-89f20600da62.png">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by kalenmike** [comment]
The server has been updated with these changes. The datasets need to be reprocessed in order for the changes to show. Frontend changes are in the current development build and will be deployed with the next release. The issue will remain open until all datasets have been updated.

**Comment by kalenmike** [comment]
Deployed and old datasets updated.
