### ISSUE TITLE
Change dataset upload string 'upload your image' -> 'upload your dataset *.zip file'

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/hub-temp#5]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

This string is incorrect. Change to 'Drag and drop your dataset *.zip file here, or select from your computer. See [Dataset HUB Tutorial](https://github.com/ultralytics/hub) to create a dataset *.zip file'

Use https://github.com/ultralytics/hub URL for 'Dataset HUB Tutorial'

<img width="1320" alt="Screenshot 2021-11-15 at 23 45 27" src="https://user-images.githubusercontent.com/26833433/141864795-120ceb85-8ae1-4975-a154-1cfb21704848.png">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by kalenmike** [comment]
The latest design has been updated and is different to the current implementation. This text will not be visible. Issue will remain open until the design has been updated.

**Comment by glenn-jocher** [comment]
@kalenmike got it! I was going to say we should task Alan with updating this popout, but sounds like it's already happening.

**Comment by kalenmike** [comment]
The string has been changed. Design improvements to follow.
