### ISSUE TITLE
Pytorch -> PyTorch in models page

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/hub-temp#6]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models

### Bug

PyTorch has a capital 'T', i.e. https://pytorch.org/

<img width="1443" alt="Screenshot 2021-11-16 at 00 01 57" src="https://user-images.githubusercontent.com/26833433/141866871-71e52ace-092e-4d44-929a-ea5f7337b659.png">

### Additional

Capitalization for our other export formats should be:

```python
        #   PyTorch:      weights = *.pt
        #   TorchScript:            *.torchscript.pt
        #   CoreML:                 *.mlmodel
        #   TensorFlow:             *_saved_model (dir)
        #   TensorFlow:             *.pb
        #   TensorFlow Lite:        *.tflite
        #   TensorFlow.js:          *_web_model (dir)
        #   ONNX:                   *.onnx
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by kalenmike** [comment]
Deployed and old models updated.
