### ISSUE TITLE
Upload coco6.zip dataset hangs on 'Processing'

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/hub-temp#8]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

I tried to upload coco6.zip but got stuck on 'Processing' step.

### Environment

OS: MacOS 11.6.1
Browser: Chrome Version 95.0.4638.69 (Official Build) (x86_64)

### Minimal Reproducible Example

1. Login to Hub (I always use Google Signin)
2. Go to Datasets tab and click Upload Dataset
3. Fill in Name and Description fields, find coco6.zip on my local machine and select for upload
4. zip uploads correctly and green 'uploading' status turns into grey 'processing' status. Waited about 10 min but no change, refresh browser does not help.

<img width="1421" alt="Screenshot 2021-11-17 at 02 37 30" src="https://user-images.githubusercontent.com/26833433/142093547-e3b0f143-035b-4a4b-94a6-180070f102e5.png">

### Additional

If I click the coco6 dataset while it's in 'processing' status I can go inside the dataset, but it's just an empty screen:

<img width="1183" alt="Screenshot 2021-11-17 at 02 38 46" src="https://user-images.githubusercontent.com/26833433/142093430-1fc811ba-1e48-469d-9727-8484b80274b7.png">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by kalenmike** [comment]
The issue has been isolated to production releases. Configuration to be updated.

**Comment by kalenmike** [comment]
This is now working on latest deployment.
